Added fr-ch localisation
lg2de/SimpleAccounting pull request #207
Opened 2022-11-08 11:00 UTC by mrzhdev

Added Swiss french localisation with translations

## Description
Added Swiss French localization with translations.
Used Zeta Resource Editor and related files are available upon request.
Probably the naming conventions are not perfect, as I am not an accountant either.

## Related issue
None.

2022-11-10 21:47 UTC, mrzhdev commented
Hi Lucas,

The main reason that I have used Swiss French localization is the use of
CHF as the currency, which is set directly in the resource file. It might
be a good idea to have currency in the settings, perhaps even a decimal
separator (Swiss decimal separator is comma and I use dot).  What do you
think?

My aim is to use your software for my accounting as a freelancer and extend
it for my personal use. Anyway, I’ll be glad to contribute, share my
development, and maintain the French localization.

++

Mirza

Le mer. 9 nov. 2022 à 09:30, Lukas Grützmacher ***@***.***> a
écrit :

> Hey @mrzhdev <https://github.com/mrzhdev>, I'm really happy that you want
> to contribute. Seams it is useful for you.
>
> I think, Swiss French is a quite specific version, isn't it?
> For me it would not be possible to verify or maintain the French
> localization in future, even less the Swiss version.
>
> I would like to ask you whether you could contribute the generic French
> version?
> This one I could maintain roughly use automatic translation.
> The verification, even more the accountant correct verification, should be
> done by native speakers.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lg2de/SimpleAccounting/pull/207#issuecomment-1308389167>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALOE5ZYY6VBNUA3FKL6UFLDWHNOK5ANCNFSM6AAAAAAR2F2ACA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-11 08:17 UTC, lg2de commented
The currency should be configurable in the project. It must not be derived from the culture settings.
This an issue which should be tracked separately.
It it is (fully) part of the resources (I've not checked that), then this is a bug.

The decimal separator should come from culture. This information is already in and should not be configured.
To reduce the effort and maximize the effect we can
1. Rename `Resources.fr-ch.resx` to `Resources.fr.resx` and update if needed.
2. Add "fr" and "fr-ch" to the culture selector. If "fr-ch" is selected the "resource culture fr" should be used together with the "ui culture fr-ch" (to get the dot as decimal separator).

2022-11-11 08:19 UTC, lg2de commented
With #127 we have already an issue for the currency configuration feature.

2022-11-11 13:29 UTC, mrzhdev commented
In resources you have the field "Label_ValueWithCurrency" with "Value (€)"
in english.
It's the only reason why I have to go with "fr-ch"instead of "fr".

Le ven. 11 nov. 2022 à 09:19, Lukas Grützmacher ***@***.***>
a écrit :

> With #127 <https://github.com/lg2de/SimpleAccounting/issues/127> we have
> already an issue for the currency configuration feature.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lg2de/SimpleAccounting/pull/207#issuecomment-1311375049>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALOE5Z63UJ72VUOHLJPHLMLWHX6QPANCNFSM6AAAAAAR2F2ACA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-11 14:33 UTC, lg2de commented
Yes, this was my fault - due to simplification for my so-far-use-cases.
Please just switch to "fr" only. You can also leave "CHF" for now.
I'll take care configuration of currency in the project incl. updating this resource.

2022-11-13 14:28 UTC, lg2de requested changes

2022-11-13 14:28 UTC, lg2de commented on src/SimpleAccounting/Properties/Resources.fr-ch.resx
> +    <value>Valeur (CHF)</value>
```suggestion
    <value>Valeur ({0})</value>
```

2022-11-13 14:28 UTC, lg2de commented on src/SimpleAccounting/Properties/Resources.fr-ch.resx
> +	<data name="Label_ValueWithCurrency" xml:space="preserve">
```suggestion
	<data name="Label_ValueWithCurrencyX" xml:space="preserve">
```

2022-11-13 14:28 UTC, lg2de commented on src/SimpleAccounting/Properties/Resources.fr-ch.resx
> +</root>
```suggestion
  <data name="Word_Currency" xml:space="preserve">
    <value>Currency</value>
  </data>
  <data name="Menu_Project_Settings_ProjectOptions" xml:space="preserve">
    <value>Options du projet</value>
  </data>
  <data name="Header_ProjectOptions" xml:space="preserve">
    <value>Modifier les options du projet</value>
  </data>
</root>
```

2022-11-13 14:28 UTC, lg2de commented on src/SimpleAccounting/Presentation/IMenuViewModel.cs
> +        bool IsSwissFrenchCulture { get; }
```suggestion
        bool IsFrenchCulture { get; }
        bool IsSwissFrenchCulture { get; }
```

2022-11-13 14:28 UTC, lg2de commented on src/SimpleAccounting/Presentation/MenuViewModel.cs
> +                this.NotifyOfPropertyChange(nameof(this.IsSwissFrenchCulture));
```suggestion
                this.NotifyOfPropertyChange(nameof(this.IsFrenchCulture));
                this.NotifyOfPropertyChange(nameof(this.IsSwissFrenchCulture));
```

2022-11-13 14:28 UTC, lg2de commented on src/SimpleAccounting/Presentation/MenuViewModel.cs
> +        public bool IsSwissFrenchCulture => this.projectData.Settings.Culture == "fr-CH";
```suggestion
        public bool IsFrenchCulture => this.projectData.Settings.Culture == "fr";
        public bool IsSwissFrenchCulture => this.projectData.Settings.Culture == "fr-CH";
```

2022-11-13 14:28 UTC, lg2de commented on src/SimpleAccounting/Presentation/ShellView.xaml
> +            <MenuItem Header="SwissFrench" Command="{Binding Menu.SwitchCultureCommand}" CommandParameter="fr-CH"
```suggestion
            <MenuItem Header="Français" Command="{Binding Menu.SwitchCultureCommand}" CommandParameter="fr"
                      IsCheckable="True" IsChecked="{Binding Menu.IsFrenchCulture, Mode=OneWay}" />
            <MenuItem Header="Français suisse" Command="{Binding Menu.SwitchCultureCommand}" CommandParameter="fr-CH"
```

2022-11-13 14:28 UTC, lg2de commented on tests/SimpleAccounting.UnitTests/Presentation/MenuViewModelTests.cs
> +            sut.IsSwissFrenchCulture.Should().BeFalse();
```suggestion
            sut.IsFrenchCulture.Should().BeFalse();
            sut.IsSwissFrenchCulture.Should().BeFalse();
```

2022-11-13 14:28 UTC, lg2de commented on src/SimpleAccounting/Properties/Resources.fr-ch.resx
> +﻿<?xml version="1.0" encoding="utf-8"?>
Please rename the file to `Resources.fr.resx`

2022-11-14 10:41 UTC, mrzhdev commented
Hi,

I have made a new push.

++

Mirza



Le dim. 13 nov. 2022 à 15:28, Lukas Grützmacher ***@***.***>
a écrit :

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/SimpleAccounting/Properties/Resources.fr-ch.resx
> <https://github.com/lg2de/SimpleAccounting/pull/207#discussion_r1020910915>
> :
>
> > +    <value>Voulez-vous clôturer l'année {0} ?</value>
>
> +  </data>
>
> +	<data name="Word_Split" xml:space="preserve">
>
> +    <value>Fractionner</value>
>
> +  </data>
>
> +	<data name="Word_BookingText" xml:space="preserve">
>
> +    <value>Texte de journalisation</value>
>
> +  </data>
>
> +	<data name="Tooltip_SplitBookingValue" xml:space="preserve">
>
> +    <value>Diviser la valeur de la journalisation</value>
>
> +  </data>
>
> +	<data name="Word_BookingNumber" xml:space="preserve">
>
> +    <value>Numéro de journalisation</value>
>
> +  </data>
>
> +	<data name="Label_ValueWithCurrency" xml:space="preserve">
>
> +    <value>Valeur (CHF)</value>
>
>
> ⬇️ Suggested change
>
> -    <value>Valeur (CHF)</value>
>
> +    <value>Valeur ({0})</value>
>
>
> ------------------------------
>
> In src/SimpleAccounting/Properties/Resources.fr-ch.resx
> <https://github.com/lg2de/SimpleAccounting/pull/207#discussion_r1020910945>
> :
>
> > +	<data name="Question_CloseYearX" xml:space="preserve">
>
> +    <value>Voulez-vous clôturer l'année {0} ?</value>
>
> +  </data>
>
> +	<data name="Word_Split" xml:space="preserve">
>
> +    <value>Fractionner</value>
>
> +  </data>
>
> +	<data name="Word_BookingText" xml:space="preserve">
>
> +    <value>Texte de journalisation</value>
>
> +  </data>
>
> +	<data name="Tooltip_SplitBookingValue" xml:space="preserve">
>
> +    <value>Diviser la valeur de la journalisation</value>
>
> +  </data>
>
> +	<data name="Word_BookingNumber" xml:space="preserve">
>
> +    <value>Numéro de journalisation</value>
>
> +  </data>
>
> +	<data name="Label_ValueWithCurrency" xml:space="preserve">
>
>
> ⬇️ Suggested change
>
> -	<data name="Label_ValueWithCurrency" xml:space="preserve">
>
> +	<data name="Label_ValueWithCurrencyX" xml:space="preserve">
>
>
> ------------------------------
>
> In src/SimpleAccounting/Properties/Resources.fr-ch.resx
> <https://github.com/lg2de/SimpleAccounting/pull/207#discussion_r1020911274>
> :
>
> > +	<data name="AccountConfiguration_IgnorePattern" xml:space="preserve">
>
> +    <value>Ignorer le modèle</value>
>
> +  </data>
>
> +	<data name="Word_Name" xml:space="preserve">
>
> +    <value>Nom</value>
>
> +  </data>
>
> +	<data name="Word_Expression" xml:space="preserve">
>
> +    <value>Expression</value>
>
> +  </data>
>
> +	<data name="AccountConfiguration_SourceDescription" xml:space="preserve">
>
> +    <value>Nom de la colonne dans le fichier d'importation (CSV)</value>
>
> +  </data>
>
> +	<data name="AccountConfiguration_IgnorePatternDescription" xml:space="preserve">
>
> +    <value>Expression régulière utilisée pour supprimer des sous-chaînes</value>
>
> +  </data>
>
> +</root>
>
>
> ⬇️ Suggested change
>
> -</root>
>
> +  <data name="Word_Currency" xml:space="preserve">
>
> +    <value>Currency</value>
>
> +  </data>
>
> +  <data name="Menu_Project_Settings_ProjectOptions" xml:space="preserve">
>
> +    <value>Options du projet</value>
>
> +  </data>
>
> +  <data name="Header_ProjectOptions" xml:space="preserve">
>
> +    <value>Modifier les options du projet</value>
>
> +  </data>
>
> +</root>
>
>
> ------------------------------
>
> In src/SimpleAccounting/Presentation/IMenuViewModel.cs
> <https://github.com/lg2de/SimpleAccounting/pull/207#discussion_r1020911542>
> :
>
> > @@ -22,6 +22,7 @@ internal interface IMenuViewModel : INotifyPropertyChanged
>
>          ICommand SwitchCultureCommand { get; }
>
>          bool IsGermanCulture { get; }
>
>          bool IsEnglishCulture { get; }
>
> +        bool IsSwissFrenchCulture { get; }
>
>
> ⬇️ Suggested change
>
> -        bool IsSwissFrenchCulture { get; }
>
> +        bool IsFrenchCulture { get; }
>
> +        bool IsSwissFrenchCulture { get; }
>
>
> ------------------------------
>
> In src/SimpleAccounting/Presentation/MenuViewModel.cs
> <https://github.com/lg2de/SimpleAccounting/pull/207#discussion_r1020911606>
> :
>
> > @@ -67,6 +67,7 @@ internal class MenuViewModel : Screen, IMenuViewModel
>
>                  this.projectData.Settings.Culture = cultureName.ToString();
>
>                  this.NotifyOfPropertyChange(nameof(this.IsGermanCulture));
>
>                  this.NotifyOfPropertyChange(nameof(this.IsEnglishCulture));
>
> +                this.NotifyOfPropertyChange(nameof(this.IsSwissFrenchCulture));
>
>
> ⬇️ Suggested change
>
> -                this.NotifyOfPropertyChange(nameof(this.IsSwissFrenchCulture));
>
> +                this.NotifyOfPropertyChange(nameof(this.IsFrenchCulture));
>
> +                this.NotifyOfPropertyChange(nameof(this.IsSwissFrenchCulture));
>
>
> ------------------------------
>
> In src/SimpleAccounting/Presentation/MenuViewModel.cs
> <https://github.com/lg2de/SimpleAccounting/pull/207#discussion_r1020911652>
> :
>
> > @@ -76,6 +77,7 @@ internal class MenuViewModel : Screen, IMenuViewModel
>
>
>
>          public bool IsGermanCulture => this.projectData.Settings.Culture == "de";
>
>          public bool IsEnglishCulture => this.projectData.Settings.Culture == "en";
>
> +        public bool IsSwissFrenchCulture => this.projectData.Settings.Culture == "fr-CH";
>
>
> ⬇️ Suggested change
>
> -        public bool IsSwissFrenchCulture => this.projectData.Settings.Culture == "fr-CH";
>
> +        public bool IsFrenchCulture => this.projectData.Settings.Culture == "fr";
>
> +        public bool IsSwissFrenchCulture => this.projectData.Settings.Culture == "fr-CH";
>
>
> ------------------------------
>
> In src/SimpleAccounting/Presentation/ShellView.xaml
> <https://github.com/lg2de/SimpleAccounting/pull/207#discussion_r1020911900>
> :
>
> > @@ -52,6 +52,8 @@
>
>                        IsCheckable="True" IsChecked="{Binding Menu.IsGermanCulture, Mode=OneWay}" />
>
>              <MenuItem Header="English" Command="{Binding Menu.SwitchCultureCommand}" CommandParameter="en"
>
>                        IsCheckable="True" IsChecked="{Binding Menu.IsEnglishCulture, Mode=OneWay}" />
>
> +            <MenuItem Header="SwissFrench" Command="{Binding Menu.SwitchCultureCommand}" CommandParameter="fr-CH"
>
>
> ⬇️ Suggested change
>
> -            <MenuItem Header="SwissFrench" Command="{Binding Menu.SwitchCultureCommand}" CommandParameter="fr-CH"
>
> +            <MenuItem Header="Français" Command="{Binding Menu.SwitchCultureCommand}" CommandParameter="fr"
>
> +                      IsCheckable="True" IsChecked="{Binding Menu.IsFrenchCulture, Mode=OneWay}" />
>
> +            <MenuItem Header="Français suisse" Command="{Binding Menu.SwitchCultureCommand}" CommandParameter="fr-CH"
>
>
> ------------------------------
>
> In tests/SimpleAccounting.UnitTests/Presentation/MenuViewModelTests.cs
> <https://github.com/lg2de/SimpleAccounting/pull/207#discussion_r1020912029>
> :
>
> > @@ -77,6 +77,7 @@ public void SwitchCultureCommand_DummyLanguage_MessageBoxShownAndConfigurationUp
>
>                  icon: MessageBoxImage.Information);
>
>              sut.IsGermanCulture.Should().BeFalse();
>
>              sut.IsEnglishCulture.Should().BeFalse();
>
> +            sut.IsSwissFrenchCulture.Should().BeFalse();
>
>
> ⬇️ Suggested change
>
> -            sut.IsSwissFrenchCulture.Should().BeFalse();
>
> +            sut.IsFrenchCulture.Should().BeFalse();
>
> +            sut.IsSwissFrenchCulture.Should().BeFalse();
>
>
> ------------------------------
>
> In src/SimpleAccounting/Properties/Resources.fr-ch.resx
> <https://github.com/lg2de/SimpleAccounting/pull/207#discussion_r1020912097>
> :
>
> > @@ -0,0 +1,570 @@
>
> +﻿<?xml version="1.0" encoding="utf-8"?>
>
>
> Please rename the file to Resources.fr.resx
>
> —
> Reply to this email directly, view it on GitHub
> <https://git [...]

2022-11-14 11:07 UTC, lg2de commented
> I have made a new push.

Why you did not took my suggestions?
1. We can use both, french and french swiss, isn't it? Or are the differences that much?
2. You must update the resources according to my recent feature update to CONFIGURE the currency.

2022-11-14 12:12 UTC, closed without merging

2022-11-14 12:25 UTC, mrzhdev commented
Hi,

1.I haven't noticed that you have changed your mind since 11 november. Also
my knowledge of github is not perfect.
2.I'll see what is happening...



Le lun. 14 nov. 2022 à 12:07, Lukas Grützmacher ***@***.***>
a écrit :

> I have made a new push.
>
> Why you did not took my suggestions?
>
>    1. We can use both, french and french swiss, isn't it? Or are the
>    differences that much?
>    2. You must update the resources according to my recent feature update
>    to CONFIGURE the currency.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lg2de/SimpleAccounting/pull/207#issuecomment-1313504429>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALOE5ZZWD35AXEJFTW6U3HTWIIMPTANCNFSM6AAAAAAR2F2ACA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-14 13:39 UTC, mrzhdev commented
I would suggest having only French and changing App.xaml.cs (see below).
Number and DateTime formats are copied from windows settings.

What do you think?


private void ApplicationStartup(object sender, StartupEventArgs e)
        {

            var settings = Settings.Default;
            if (!string.IsNullOrEmpty(settings.Culture))
            {
                var culture =
(CultureInfo)CultureInfo.GetCultureInfo(settings.Culture).Clone();
                //copy current user settings
                culture.NumberFormat =
CultureInfo.CurrentCulture.NumberFormat;
                culture.DateTimeFormat =
CultureInfo.CurrentCulture.DateTimeFormat;
                //apply culture to current thread
                CultureInfo.CurrentCulture = CultureInfo.CurrentUICulture =
culture;

            }
            else
            {
                // set control culture according to system culture
                //
https://stackoverflow.com/questions/4041197/how-to-set-and-change-the-culture-in-wpf
                FrameworkElement.LanguageProperty.OverrideMetadata(
                    typeof(FrameworkElement),
                    new
FrameworkPropertyMetadata(XmlLanguage.GetLanguage(CultureInfo.CurrentCulture.IetfLanguageTag)));
            }

        }

Le lun. 14 nov. 2022 à 13:25, Mirza Hernic ***@***.***> a écrit :

> Hi,
>
> 1.I haven't noticed that you have changed your mind since 11 november.
> Also my knowledge of github is not perfect.
> 2.I'll see what is happening...
>
>
>
> Le lun. 14 nov. 2022 à 12:07, Lukas Grützmacher ***@***.***>
> a écrit :
>
>> I have made a new push.
>>
>> Why you did not took my suggestions?
>>
>>    1. We can use both, french and french swiss, isn't it? Or are the
>>    differences that much?
>>    2. You must update the resources according to my recent feature
>>    update to CONFIGURE the currency.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/lg2de/SimpleAccounting/pull/207#issuecomment-1313504429>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ALOE5ZZWD35AXEJFTW6U3HTWIIMPTANCNFSM6AAAAAAR2F2ACA>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-11-15 20:50 UTC, lg2de commented
I guess we should start again from the beginning...
You want to have French (swiss) localization and French swiss currency printing.
[I learned meanwhile](https://learn.microsoft.com/en-us/globalization/locale/currency-formatting) that "French swiss" is the one and only area where we have a difference in number formatting (.) and currency formatting (,), correct.
This means I/we need not only to change the available cultures or resources, but also all occurrences for currency formatting. This is quite big effort. But I think it should be correct.

I introduced manual culture selection because I faced some situations where automatic detection (system culture) was not the desired result.
But when I start selecting the culture I would like be consistent. So I do not like to decouple these settings.

I think with your initial commit and my suggestions we are quite close to the correct solution for you. Then we "only" need to change "all the currency formatting". (This I would like to handle in a different PR.)

If you still want to contribute this feature, please
1. create a new PR with your initial commit (I recommend to use a branch in your repository too)
2. rebase it on my main
3. Apply the suggesions above (just provide French - without "swiss")

If your computer is configured to "French swiss" SimpleAccounting with the "<System>" selection should automatically show the "French" localization and use the French swiss formatting.

2022-11-16 11:51 UTC, mrzhdev commented
I have just found out appropriate WPF solution:

·       Adding to control ->
xmlns:globalization="clr-namespace:System.Globalization;assembly=mscorlib"

·       Adding to binding -> , ConverterCulture={x:Static
globalization:CultureInfo.CurrentCulture}

It’s working in designtime and runtime

https://www.codeproject.com/Tips/1004834/Binding-with-Respect-to-CurrentCulture

Exemple (ShellView.xaml line 157):

            <DataGrid.Columns>

              <DataGridTextColumn Header="{x:Static
properties:Resources.Word_Date}" Width="60"

                                  Binding="{Binding Date,
StringFormat=\{0:d\}, ConverterCulture={x:Static
globalization:CultureInfo.CurrentCulture}}" />

              <DataGridTextColumn Header="{x:Static
properties:Resources.Word_BookingNumber_Short}" Width="75"

                                  Binding="{Binding Identifier}" />

              <DataGridTextColumn Header="{x:Static
properties:Resources.Word_BookingText}" Width="200"

                                  Binding="{Binding Text}" />

              <DataGridTextColumn Header="{x:Static
properties:Resources.Word_Value}" Width="70"

                                  Binding="{Binding Value,
StringFormat=\{0:0.00\}, ConverterCulture={x:Static
globalization:CultureInfo.CurrentCulture}}"

Le mer. 16 nov. 2022 à 11:54, Mirza Hernic ***@***.***> a écrit :

> I’ll also explain what is happening, as there is some misunderstanding.
>
> In "fr" and "fr-ch" the decimal separator is "," but on my side, I prefer
> to use ".". To solve my issue, I have found a partial workaround:
>
> ·       Changed Windows regional settings from (decimal separator) "," to
> "."
>
> ·       Changed ApplicationStartup in your application to load user
> settings (my Windows regional settings)
>
> ·       In this case issue with dot is OK but there is issue with WPF
> date format
>
> When I’m loading "System," it should use my Windows regional settings, but
> WPF is displaying "," and rapport is using "."
>
> ·       In this case issue with WPF date format is OK but there is issue
> with dot (comma is displayed)
>
>
>
> I’m ok to contribute but I also have other priorities. Also, my git
> knowledge is not perfect, and I have to pay attention to what I’m doing.
>
> Le mar. 15 nov. 2022 à 21:50, Lukas Grützmacher ***@***.***>
> a écrit :
>
>> I guess we should start again from the beginning...
>> You want to have French (swiss) localization and French swiss currency
>> printing.
>> I learned meanwhile
>> <https://learn.microsoft.com/en-us/globalization/locale/currency-formatting>
>> that "French swiss" is the one and only area where we have a difference in
>> number formatting (.) and currency formatting (,), correct.
>> This means I/we need not only to change the available cultures or
>> resources, but also all occurrences for currency formatting. This is quite
>> big effort. But I think it should be correct.
>>
>> I introduced manual culture selection because I faced some situations
>> where automatic detection (system culture) was not the desired result.
>> But when I start selecting the culture I would like be consistent. So I
>> do not like to decouple these settings.
>>
>> I think with your initial commit and my suggestions we are quite close to
>> the correct solution for you. Then we "only" need to change "all the
>> currency formatting". (This I would like to handle in a different PR.)
>>
>> If you still want to contribute this feature, please
>>
>>    1. create a new PR with your initial commit (I recommend to use a
>>    branch in your repository too)
>>    2. rebase it on my main
>>    3. Apply the suggesions above (just provide French - without "swiss")
>>
>> If your computer is configured to "French swiss" SimpleAccounting with
>> the "" selection should automatically show the "French" localization and
>> use the French swiss formatting.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/lg2de/SimpleAccounting/pull/207#issuecomment-1315847360>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ALOE5ZZWDNAAITAR7FC6YBLWIPZQNANCNFSM6AAAAAAR2F2ACA>
>> .
>> You are receiving this because you modified the open/close state.Message
>> ID: ***@***.***>
>>
>

2022-11-17 13:25 UTC, lg2de commented
I don't want to miss your localization.
Therefore I created a new PR based on your work (cherry-pick).
Please review #213.

Further I understand what you want to change to archive correct visualization of overwritten regional settings.
A PR is welcome. Otherwise we should track this as an issue and I'll take care later.

Please note that - as stated before - we should also switch from "number formatting" to "currency formatting" to be fully correct in "swiss french" localization.

2022-11-18 11:08 UTC, mrzhdev commented
Nicely done.

I have taken a look, and everything is fine.

On my side, I'll do my best to submit a consistent PR aligned with coding
style.

I'll keep following what is happening on the project and keep the French
translations updated.

Le jeu. 17 nov. 2022 à 14:25, Lukas Grützmacher ***@***.***>
a écrit :

> I don't want to miss your localization.
> Therefore I created a new PR based on your work (cherry-pick).
> Please review #213 <https://github.com/lg2de/SimpleAccounting/pull/213>.
>
> Further I understand what you want to change to archive correct
> visualization of overwritten regional settings.
> A PR is welcome. Otherwise we should track this as an issue and I'll take
> care later.
>
> Please note that - as stated before - we should also switch from "number
> formatting" to "currency formatting" to be fully correct in "swiss french"
> localization.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lg2de/SimpleAccounting/pull/207#issuecomment-1318634234>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALOE5Z225OKE3U73ZSA6ZGDWIYW5JANCNFSM6AAAAAAR2F2ACA>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>