Create booking entry like ... #187
lg2de/SimpleAccounting pull request #231
Opened 2023-01-29 16:01 UTC by mrzhdev

## Description
Feature for creating new bookings from existing ones.
Added  a context menu for booking entries.

## Related issue
#187

2023-02-12 17:14 UTC, lg2de requested changes
Thanks for you contribution and sorry for the delay!
Please also add a unit test that verifies that duplicating an entry will not change the old one.

2023-02-12 17:14 UTC, lg2de commented on src/SimpleAccounting/Model/ProjectData.cs
> +        private EditBookingViewModel BookingFromJournal(AccountingDataJournalBooking journalEntry, bool isEdit, bool showInactiveAccounts)
`private` methods should be placed after `public` (and `protected`) methods.
If you have "ReSharper" or "Rider" please try the cleanup profile "lg2".

2023-02-12 17:14 UTC, lg2de commented on src/SimpleAccounting/Model/ProjectData.cs
> +
```suggestion
```

2023-02-12 17:14 UTC, lg2de commented on src/SimpleAccounting/Model/ProjectData.cs
> +        private EditBookingViewModel BookingFromJournal(AccountingDataJournalBooking journalEntry, bool isEdit, bool showInactiveAccounts)
```suggestion
        private EditBookingViewModel CreateEditViewModel(AccountingDataJournalBooking journalEntry, bool editMode, bool showInactiveAccounts)
```

2023-02-12 17:14 UTC, lg2de commented on src/SimpleAccounting/Model/ProjectData.cs
> +                editMode: isEdit)
```suggestion
                editMode)
```

2023-02-12 17:14 UTC, lg2de commented on src/SimpleAccounting/Model/ProjectData.cs
> +            var bookingModel = this.BookingFromJournal(journalEntry, false, showInactiveAccounts);
```suggestion
            var bookingModel = this.BookingFromJournal(journalEntry, editMode: false, showInactiveAccounts); 
```

2023-02-12 17:14 UTC, lg2de commented on src/SimpleAccounting/Model/ProjectData.cs
> +            var bookingModel = this.BookingFromJournal(journalEntry, true, showInactiveAccounts);
```suggestion
            var bookingModel = this.BookingFromJournal(journalEntry, editMode: true, showInactiveAccounts);
```

2023-02-12 17:14 UTC, lg2de commented on src/SimpleAccounting/Properties/Resources.de.resx
> +    <value>Duplikat</value>
```suggestion
    <value>Kopie erstellen</value>
```

2023-02-12 17:14 UTC, lg2de commented on src/SimpleAccounting/Properties/Resources.resx
> +    <value>Duplicate</value>
```suggestion
    <value>Create copy</value>
```

2023-02-12 17:14 UTC, lg2de commented on src/SimpleAccounting/Properties/Resources.resx
> +    <value>Duplicate</value>
Please change french version accordingly.

2023-02-12 17:14 UTC, lg2de commented on src/SimpleAccounting/Presentation/ShellView.xaml
> +            <DataGrid.ContextMenu>
When starting context menu, could you please also add the "edit" option?

2023-02-12 17:14 UTC, lg2de commented on src/SimpleAccounting/Model/ProjectData.cs
> +            var journalEntry = this.CurrentYear.Booking[item.StorageIndex];
```suggestion

            var journalEntry = this.CurrentYear.Booking[item.StorageIndex];
```

2023-02-25 11:20 UTC, lg2de commented
@mrzhdev Are you still willing to implement my suggestions?

2023-02-28 07:04 UTC, mrzhdev commented on src/SimpleAccounting/Properties/Resources.resx
> +    <value>Duplicate</value>
Créer une copie

2023-02-28 07:09 UTC, mrzhdev commented
I'm quite busy these days and I do not have the efficiency to implement
your suggestions in reasonable delay.



Le sam. 25 févr. 2023 à 12:21, Lukas Grützmacher ***@***.***>
a écrit :

> @mrzhdev <https://github.com/mrzhdev> Are you still willing to implement
> my suggestions?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lg2de/SimpleAccounting/pull/231#issuecomment-1445059150>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALOE5Z6GHHRTDIYF7GCLJ4LWZHTJZANCNFSM6AAAAAAUKKFDGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-28 07:42 UTC, merged